### ISSUE TITLE
script fails

### ISSUE THREAD

**Issue by rabarar** [NiklasRosenstein/xcode-cltools-installer#8]
Ran the script against the 6.1.1 cli tools - fails below...

```
sudo ./install ~/Downloads/commandlinetoolsosx10.10forxcode6.1.1.dmg ~/src/cli_Xcode/xcode_cli_6.11
$ hdiutil mount /Users/robert/Downloads/commandlinetoolsosx10.10forxcode6.1.1.dmg
$ xar -C /tmp/tmpfNV2yO -xf '/Volumes/Command Line Developer Tools/Command Line Tools (OS X 10.10).pkg'
$ xar -C /tmp/tmpsPqWDB -xf /tmp/tmpfNV2yO/DevSDK_OSX1010.pkg
Error opening xar archive: /tmp/tmpfNV2yO/DevSDK_OSX1010.pkg
$ hdiutil unmount '/Volumes/Command Line Developer Tools'
Traceback (most recent call last):
  File "./install", line 473, in <module>
    sys.exit(main())
  File "./install", line 448, in main
    install_pkg(packages['sdk'], args.dest)
  File "./install", line 360, in install_pkg
    unpack_pkg(pkg_filename, tmpdir)
  File "./install", line 345, in unpack_pkg
    System.call('xar', '-C', dest, '-xf', pkg_filename)
  File "./install", line 76, in call
    raise self.ExitError(args, process.returncode)
```

**Comment by NiklasRosenstein** [comment]
This repository hasn't been updated since a while, I might get to it mid-october. Thanks for reporting the issue

**Comment by rabarar** [comment]
Thanks for the reply -- I just used Xcode-select and that worked for me :)
